# Generated by Django 3.0.4 on 2020-03-12 13:39
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0007_auto_20200309_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='images',
            field=models.ImageField(
                blank=True, default=None, upload_to=b'images'),
        ),
    ]
