# Generated by Django 2.1.5 on 2020-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0013_auto_20200324_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='imageURL',
            field=models.CharField(blank=True, default=None, max_length=180, null=True),
        ),
    ]
