# Generated by Django 3.0.4 on 2020-03-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='Type',
            field=models.CharField(default='history', max_length=180),
        ),
        migrations.AddField(
            model_name='point',
            name='declaredClass',
            field=models.CharField(default='history', max_length=180),
        ),
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.FloatField(default=21.2),
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.FloatField(default=21.2),
        ),
        migrations.AddField(
            model_name='point',
            name='objectID',
            field=models.IntegerField(default=0),
        ),
    ]
