# Generated by Django 3.0.4 on 2020-03-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0006_auto_20200309_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='title',
            field=models.CharField(max_length=180),
        ),
    ]
