# Generated by Django 3.0.4 on 2020-03-17 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_auto_20200317_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectID', models.IntegerField(blank=True, default=None, null=True)),
                ('title', models.CharField(max_length=180)),
                ('longDescription', models.TextField(blank=True, default=None, null=True)),
                ('shortDescription', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('declaredClass', models.CharField(blank=True, default=None, max_length=180, null=True)),
                ('Type', models.CharField(blank=True, default=None, max_length=180, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='image',
            name='point',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.Point'),
        ),
    ]
