# Generated by Django 3.0.4 on 2020-03-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_auto_20200308_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='description',
        ),
        migrations.AddField(
            model_name='point',
            name='longDescription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='shortDescription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='Type',
            field=models.CharField(blank=True, default=None, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='declaredClass',
            field=models.CharField(blank=True, default=None, max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='objectID',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
