# Generated by Django 3.0.4 on 2020-03-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_point_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='images',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
